"use client"

import { useState } from "react"
import { Check, Copy, KeyRound, LockKeyhole, Plus, ShieldCheck, Smartphone } from "lucide-react"
import { useJellyfin } from "@/components/jellyfin-provider"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function IpAdminView() {
  const { currentIp, publicIpVerified, blockedIps, blockIp, activation, generateActivationCode } = useJellyfin()
  const [value, setValue] = useState("")
  const [message, setMessage] = useState("")
  const [newCode, setNewCode] = useState("")
  function addIp() { const ip = value.trim(); if (!ip) return; blockIp(ip); setValue(""); setMessage(`${ip} a été ajouté à la liste noire.`); window.setTimeout(() => setMessage(""), 2600) }
  function createCode() { setNewCode(generateActivationCode()) }
  return <main className="min-h-dvh px-4 py-10 sm:px-8"><div className="mx-auto max-w-5xl"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.28em] text-cyan-200/70">Centre de contrôle</p><h1 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">Sécurité réseau</h1><p className="mt-3 max-w-2xl text-white/50">Validez les nouvelles adresses avec un code temporaire et gardez le contrôle des appareils autorisés.</p></div>
    <div className="grid gap-4 md:grid-cols-3"><div className="glass-panel p-5"><ShieldCheck className="size-5 text-emerald-300" /><p className="mt-4 text-xs uppercase tracking-wider text-white/40">IP publique réelle</p><p className="mt-2 font-mono text-xl">{currentIp}</p><p className="mt-2 text-xs text-emerald-200">{publicIpVerified ? "Vérifiée côté serveur" : "En attente du proxy"}</p></div><div className="glass-panel p-5"><Smartphone className="size-5 text-cyan-200" /><p className="mt-4 text-xs uppercase tracking-wider text-white/40">Appareils autorisés</p><p className="mt-2 text-3xl font-semibold">{activation.activated}<span className="text-lg text-white/35"> / {activation.limit}</span></p><p className="mt-2 text-xs text-white/45">Une nouvelle demande est requise après la limite.</p></div><div className="glass-panel p-5"><LockKeyhole className="size-5 text-amber-200" /><p className="mt-4 text-xs uppercase tracking-wider text-white/40">Protection active</p><p className="mt-2 font-semibold">Code requis sur nouvelle IP</p><p className="mt-2 text-xs text-white/45">Les codes ne sont jamais envoyés dans l&apos;URL.</p></div></div>
    <section className="glass-panel mt-5 p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="flex items-center gap-2 font-semibold"><KeyRound className="size-5 text-cyan-200" />Codes d&apos;activation</h2><p className="mt-1 text-sm text-white/45">Générez un code à communiquer uniquement à l&apos;appareil de confiance.</p></div><Button onClick={createCode} className="bg-cyan-200 text-slate-950 hover:bg-cyan-100"><Plus data-icon="inline-start" /> Générer un code</Button></div>{newCode ? <div className="mt-5 flex items-center gap-3 rounded-xl border border-cyan-200/25 bg-cyan-200/[.08] p-4"><code className="flex-1 font-mono text-lg tracking-widest text-cyan-100">{newCode}</code><Button variant="outline" size="icon" aria-label="Copier le code" onClick={() => navigator.clipboard.writeText(newCode)} className="border-white/15 bg-transparent"><Copy /></Button></div> : null}<div className="mt-5 grid gap-2 sm:grid-cols-2">{activation.codes.map((code) => <div key={code} className="rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 font-mono text-sm text-white/65">{code}</div>)}</div></section>
    <section className="glass-panel mt-5 p-5 sm:p-6"><h2 className="flex items-center gap-2 font-semibold"><LockKeyhole className="size-5 text-rose-200" />Liste noire IP</h2><p className="mt-1 text-sm text-white/45">Bloquez une adresse publique après analyse.</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Ex. 203.0.113.24" className="h-11 border-white/15 bg-white/[.06] font-mono text-white placeholder:text-white/30" aria-label="Adresse IP à bloquer" /><Button onClick={addIp} className="h-11 bg-rose-300 text-slate-950 hover:bg-rose-200"><Plus data-icon="inline-start" /> Bloquer l&apos;IP</Button></div>{message ? <p className="mt-3 flex items-center gap-2 text-sm text-emerald-200"><Check className="size-4" />{message}</p> : null}<div className="mt-5 flex flex-wrap gap-2">{blockedIps.map((ip) => <span key={ip} className="rounded-full border border-rose-200/20 bg-rose-200/[.08] px-3 py-1.5 font-mono text-xs text-rose-100">{ip}</span>)}</div></section>
  </div></main>
}
