"use client"

import { useState } from "react"
import { Ban, Check, Globe2, Plus, ShieldCheck, Trash2 } from "lucide-react"
import { useJellyfin } from "@/components/jellyfin-provider"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function IpAdminView() {
  const { blockedIps, blockIp, unblockIp } = useJellyfin()
  const [value, setValue] = useState("")
  const [message, setMessage] = useState("")
  function addIp() { const ip = value.trim(); if (!ip) return; blockIp(ip); setValue(""); setMessage(`${ip} a été ajouté à la liste noire.`); window.setTimeout(() => setMessage(""), 2600) }
  return <main className="min-h-dvh px-4 py-10 sm:px-8"><div className="mx-auto max-w-5xl"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.28em] text-rose-200/70">Centre de contrôle</p><h1 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">Adresses bloquées</h1><p className="mt-3 max-w-xl text-white/50">Gérez les connexions qui ne peuvent plus accéder à Jellyfin-perso.</p></div><div className="glass-panel p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-rose-300/15 text-rose-200"><Ban className="size-5" /></span><div><h2 className="font-semibold">Bloquer une adresse</h2><p className="text-sm text-white/45">Ajoutez une IP IPv4 ou IPv6.</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Input value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing && event.keyCode !== 229) addIp() }} placeholder="Ex. 192.168.1.24" className="h-11 border-white/15 bg-white/[.06] font-mono text-white placeholder:text-white/30" aria-label="Adresse IP à bloquer" /><Button onClick={addIp} className="h-11 bg-rose-300 text-slate-950 hover:bg-rose-200"><Plus data-icon="inline-start" /> Bloquer l&apos;IP</Button></div>{message ? <p className="mt-3 flex items-center gap-2 text-sm text-emerald-200"><Check className="size-4" />{message}</p> : null}</div><div className="glass-panel mt-5 overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4 sm:px-6"><div><h2 className="font-semibold">Liste noire</h2><p className="text-sm text-white/45">{blockedIps.length} adresse{blockedIps.length > 1 ? "s" : ""} bloquée{blockedIps.length > 1 ? "s" : ""}</p></div><ShieldCheck className="size-5 text-emerald-200" /></div>{blockedIps.length ? <div className="divide-y divide-white/10">{blockedIps.map((ip) => <div key={ip} className="flex items-center justify-between gap-4 px-5 py-4 sm:px-6"><div className="flex items-center gap-3"><Globe2 className="size-4 text-white/40" /><span className="font-mono text-sm">{ip}</span></div><Button variant="ghost" size="sm" onClick={() => unblockIp(ip)} className="text-white/50 hover:bg-emerald-300/10 hover:text-emerald-200"><Trash2 data-icon="inline-start" /> Retirer</Button></div>)}</div> : <div className="px-6 py-12 text-center text-sm text-white/45">Aucune adresse bloquée pour le moment.</div>}</div></div></main>
}
